GET http://localhost:2000

###

POST http://localhost:2000/api/signIn
Content-Type: application/json

{
    "username": "Korenium",
    "password": "Korenium",
    "name": "Korenium"
}

###

POST http://localhost:2000/api/signUp
Content-Type: application/json

{
    "username": "Korenium",
    "password": "Korenium",
    "name": "Korenium"
}